# Generated by Django 5.0.7 on 2024-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='celery_task_id',
        ),
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('triggered', 'Triggered')], default='created', max_length=10),
        ),
    ]
