# Generated by Django 5.0.7 on 2024-07-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_remove_alert_celery_task_id_alter_alert_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('triggered', 'Triggered'), ('deleted', 'Deleted')], default='created', max_length=10),
        ),
    ]
